### PR TITLE
SFTP: Check for the correct key type

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by terrafrost** [comment]
I cherry picked this to the 1.0 branch and merged to master:

https://github.com/phpseclib/phpseclib2_compat/commit/cfe43e264e60ddb4d3694626567364521bec5a07

Thanks!

And sorry for the delay - it's been a super busy week!

**Comment by IonBazan** [comment]
@terrafrost any chances to tag this bugfix as 1.0.4?

**Comment by claudepache** [comment]
@terrafrost I just stumbled on this bug. Any chance to have soon a release with the bugfix?

**Comment by terrafrost** [comment]
> @terrafrost I just stumbled on this bug. Any chance to have soon a release with the bugfix?

Done!

**Pull request closed without merging**
